// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.

package frc.robot.subsystems;

import com.ctre.phoenix.ErrorCode;
import com.ctre.phoenix.led.CANdle;
import com.ctre.phoenix.led.CANdle.LEDStripType;
import com.ctre.phoenix.led.CANdleConfiguration;
import com.ctre.phoenix.led.CANdleFaults;
import com.ctre.phoenix.led.RainbowAnimation;

/** Add your docs here. */
public class LEDDriver {
CANdle candle = new CANdle(7); // creates a new CANdle with ID 0

public LEDDriver() {
    CANdleConfiguration config = new CANdleConfiguration();
    config.stripType = LEDStripType.RGB; // set the strip type to RGB
    config.brightnessScalar = 0.5; // dim the LEDs to half brightness
    candle.configAllSettings(config);
} 

    public void setLEDs(int r, int g, int b) {
        candle.setLEDs(r, g, b);
    }

    public void setLEDsToWhite() {
        candle.setLEDs(255, 255, 255); // set the CANdle LEDs to white
    }
    
    public void animateRainbow() {
        RainbowAnimation rainbowAnim = new RainbowAnimation(1, 0.5, 64);
        candle.animate(rainbowAnim);
    }
   
    public void printErrorsAndFaults() {
        ErrorCode error = candle.getLastError(); // gets the last error generated by the CANdle
        CANdleFaults faults = new CANdleFaults();
        ErrorCode faultsError = candle.getFaults(faults); // fills faults with the current CANdle faults; returns the last error generated
        candle.clearStickyFaults(); // clears the current CANdle faults
        System.out.println("Error: " + error + " Faults: " + faultsError);
    }
}
